---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-set-k8s
  namespace:
spec:
  interval: 12h
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: arc-systems
      version: 0.10.1
  values:
    githubConfigUrl: https://github.com/Benjamin-Etheredge/mono
    githubConfigSecret: github-token
    minRunners: 1
    # controllerServiceAccount:
    #   namespace: arc-systems
    #   # Name must line up with the above chart release name eg `github-actions-scale-set-controller`. Install the above chart and see what SA name it makes.
    #   name: arc-gha-rs-controller
    containerMode:
      # Needed, even if the docs say it isn't.
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-single"
        resources:
          requests:
            storage: 1Gi
