---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: ollama
spec:
  interval: 12h
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 12h
  # increasing timeout for model pulling
  timeout: 30m
  chart:
    spec:
      chart: ollama
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
      version: 1.2.0
  values:
    ollama:
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      models:
        insecure: true
        pull:
          - llama3.2
          - nomic-embed-text
          - qwen2.5-coder:7b
          - qwen2.5-coder:14b
          - qwen2.5-coder:32b
          - llama3.2-vision:11b
          - deepseek-r1:7b
          - deepseek-r1:14b
          - deepseek-r1:32b
          - deepseek-r1:70b
    # nodeSelector:
    #   nvidia.com/gpu.product: NVIDIA-GeForce-RTX-3090-Ti
    persistentVolume:
      enabled: true
      size: 200Gi
      storageClass: "nfs-csi"
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      hosts:
        # - host: ollama.etheredge.dev
        #   paths:
        #     - path: /
        #       pathType: Prefix
        - host: ollama.k8s.local
          paths:
            - path: /
              pathType: Prefix
---
# Adding external ingress with auth
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-auth
  namespace: ollama
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
    - host: ollama.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  number: 11434
