---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: webui
spec:
  interval: 12h
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: webui
spec:
  interval: 12h
  chart:
    spec:
      chart: open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-webui
      version: 5.10.0
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - "http://ollama.k8s.local"
    pipelines:
      enabled: true
    persistence:
      enabled: true
      size: 128Gi
    service:
      type: NodePort
      nodePort: 31435
    ingress:
      enabled: true
      class: nginx
      host: "webui.k8s.local"
      additionalHosts:
        - "webui.etheredge.dev"
