---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: webui
spec:
  interval: 30m0s
  url: https://helm.openwebui.com/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: webui
spec:
  interval: 10m0s
  chart:
    spec:
      chart: open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-webui
      version: 5.4.0
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - "http://ollama.k8s.lan"
    pipelines:
      enabled: true
    service:
      type: NodePort
      nodePort: 31435
    ingress:
      enabled: true
      class: nginx
      host: "webui.k8s.lan"
      additionalHosts:
        - "webui.etheredge.dev"
