---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 12h
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 12h
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 5.4.0
  valuesFrom:
    - kind: Secret
      name: minio-values
  values:
    mode: standalone
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - minio.etheredge.dev
        - minio.k8s.local
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/server-snippet: |
          client_max_body_size 0;
        nginx.ingress.kubernetes.io/configuration-snippet: |
          chunked_transfer_encoding off;
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - console-minio.etheredge.dev
        - console-minio.k8s.local
    persistence:
      enabled: true
      storageClass: "nfs-csi"
