---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m0s
  url: https://charts.min.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m0s
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 5.4.0
  valuesFrom:
    - kind: Secret
      name: minio-values
  values:
    mode: standalone
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - minio.k8s.lan
        # - minio.etheredge.dev
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - console-minio.k8s.lan
        # - console-minio.etheredge.dev
    