---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-vibrations
  namespace: apps
  labels:
    app: air-vibrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: air-vibrations
  template:
    metadata:
      labels:
        app: air-vibrations
    spec:
      containers:
        - name: air-vibrations
          image: docker.io/etheredgeb/air-vibrations:1.0.0 # {"$imagepolicy": "flux-system:air-vibrations"}
          env:
            - name: GRADIO_SERVER_NAME
              value: "0.0.0.0"
            - name: GRADIO_SERVER_PORT
              value: "7860"
          ports:
            - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: air-vibrations
  namespace: apps
spec:
  selector:
    app: air-vibrations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: air-vibrations
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: air-vibrations.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-vibrations
                port:
                  number: 80
    - host: air-vibrations.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-vibrations
                port:
                  number: 80
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImageRepository
# metadata:
#   name: air-vibrations
#   namespace: flux-system
# spec:
#   image: docker.io/etheredgeb/air-vibrations
#   interval: 5m
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImagePolicy
# metadata:
#   name: air-vibrations
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: air-vibrations
#   policy:
#     semver:
#       range: '>=1.0.0'
