apiVersion: apps/v1
kind: Deployment
metadata:
  name: itty
  namespace: apps
  labels:
    app: itty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itty
  template:
    metadata:
      labels:
        app: itty
    spec:
      containers:
        - name: itty
          image: docker.io/etheredgeb/itty:1.0.0 # {"$imagepolicy": "flux-system:itty"}
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: itty
  namespace: apps
spec:
  selector:
    app: itty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itty
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: itty.k8s.local
      http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itty
              port:
                number: 80
    - host: itty.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itty
                port:
                  number: 80
