---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: reddit-sums
  namespace: flux-system
spec:
  image: docker.io/etheredgeb/reddit-sums
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: reddit-sums
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: reddit-sums
  policy:
    semver:
      range: '>=1.0.0'
