apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-sums
  namespace: apps
  labels:
    app: reddit-sums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-sums
  template:
    metadata:
      labels:
        app: reddit-sums
    spec:
      containers:
        - name: reddit-sums
          image: docker.io/etheredgeb/reddit-sums:1.0.6 # {"$imagepolicy": "flux-system:reddit-sums"}
          ports:
            - containerPort: 8501
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: reddit-secret
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reddit-secret
                  key: CLIENT_SECRET
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reddit-secret
                  key: PASSWORD
            - name: USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: reddit-secret
                  key: USER_AGENT
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: reddit-secret
                  key: USERNAME
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-sums
  namespace: apps
spec:
  selector:
    app: reddit-sums
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-sums
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: reddit-sums.k8s.local
      http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: reddit-sums
              port:
                number: 80
    - host: reddit-sums.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reddit-sums
                port:
                  number: 80
