---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: reddit-sums
  namespace: apps
spec:
  imageRepositoryRef:
    name: reddit-sums
  policy:
    semver:
      range: '>=1.0.0'
