apiVersion: v1
kind: Secret
metadata:
  name: reddit-secret
  namespace: apps
type: Opaque
stringData:
  CLIENT_ID: ENC[AES256_GCM,data:7dQ0vv1F/vG50tluJmpfPkGF9W12pg==,iv:LqKifOdH81Poo3ULjSnSYEQA8N0X8tuBv3Phb5r2GHQ=,tag:A6v4uaTLS1xEOMHp8mU3kg==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:JcKncYq+kxIv7XZzhwponlQziY2PJU0pa2YGAQ3T,iv:icra7vpIdDnmfdKI17/Ak6X2L4Hu7yZCzNBJcGxsuK4=,tag:nUIo0xzJQob85SAUSj57Vw==,type:str]
  PASSWORD: ENC[AES256_GCM,data:j/plQVWMfBZt+wnsmr5e3LXbmOOVh7maJdsHXkNsWMH7iYrrUMXmsF3oHWxyDHVIyZtEClx+120+qVXY7yNvYQ==,iv:tccPsoCkY2bmUE9Cuc4uhaeh3ztP2JZhVr8gckeV4s8=,tag:RaOB4ytg80AMcTkotVoAvA==,type:str]
  USER_AGENT: ENC[AES256_GCM,data:XOLYUYX3Lr1m,iv:0pAqy8sJXqnTP8ZgLqbvPDYEnnOT1UzG4XGOZSAMwqc=,tag:hd+cKMhSftqhcwtttNUgXg==,type:str]
  USERNAME: ENC[AES256_GCM,data:ghey0IHENASaoxIOMIg=,iv:jUfJgC03yhpq7Y4HZFFojUxEpaESl6B2clnWaVQglvY=,tag:nxmzzORuifM73PIw6Jp0dA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-02-08T01:13:57Z"
  mac: ENC[AES256_GCM,data:5MQ/KeCHcm/Atu+0VraisIZEASnQU+N3WPMQ5AL+9hUHP6/vIXaT07b/3NiT8pXPJcKnyfC1qg86btIXwcgzQU5gP8oeHZo4hpjHe+/pSYJScNe41t/81jPZOBZwev/EMgWyHIr3zM/g4X4cjWgGDh/CYx9WXgaD/Tpefhf4F9I=,iv:NItZ5zy0uC2AiSuQnNAlz8pjxEM1ISpuphimRUxBStU=,tag:AYUwppTyQthF9bsOxdjd8A==,type:str]
  pgp:
    - created_at: "2025-02-08T01:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA0tk1fhnWD/CAQ/9GV+sGBhvAD3lvqvz8zqYgekQ819VXZ29c982ENKLFON1
        aW1EwivNqd48/zw9J8Cd3l+DvfeHfI/BWSI5HHibMihUpwAPxiiZsSWzrAeQmMcd
        4pFu9vtVPpPM+VtleKhkGxPJUTbcRgw4sXG4nwM+gguq8qj85+x61p3DHcE1Y7uG
        4BjMypYccV4rA8fYcAs44OCo1RArXKVbi4WyC2h8epGqoR4onSwLD904ftj+UR0H
        UeYcP+vK2CFxoGgdubwgXp8zsG4xhE0QsmTo96my8L51uPMV0ZQCGIrWIzPtBSuM
        Thn5HfmwX+FOYZb1tPNhtYWTjTHC5QH3yU2HjsoepX4ClJ0ckB8jANYr/S4O+3Lm
        B/2LwBdJg3vGYvVbroo9PkdCa2JpIv+VvpGtEYnf+H5cfSaD8K9MenldEomCBXfR
        kCaB7IAH7UFJkGdgDH/iQ77WArNzTmMRJptxx+BmTJ1Y6/pYkMlOCMcdArxqqOpL
        zyV1+L2wnfAS2Yw9pqRtDF8wBIqp0s6psvGvnek4+ypQQDsDdC7M9AZ5bpBo6/D8
        e9kylAgfLQVJf+FVCX+tK2xUjN/galt0/4pww5d3RQIGRTiANkyhfIvzpRpHdoJd
        920UYl6vgg9SoODOww8tbn8VC+IDDyOFCOjJaq4t61nIKINU506r2KrrZ+MuZrnS
        XAHEPqWZivZNxTqIbIFy1UjdzkWhjJ2omY10jjm+xVHrTcktk/YmSDJGkUvfRwde
        H12MmQW6o8ND7bQfBbTOQ6EX4+Xzgs1VhxyuS6EwgHmZKIZ+ybL+MqEQpp4m
        =FwBe
        -----END PGP MESSAGE-----
      fp: D862C8B21CC95A554ADBF4FB5E766DCE1FF979DB
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
