---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcam-demo
  namespace: apps
  labels:
    app: webcam-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcam-demo
  template:
    metadata:
      labels:
        app: webcam-demo
    spec:
      containers:
        - name: webcam-demo
          image: docker.io/etheredgeb/webcam-demo
          env:
            - name: GRADIO_SERVER_NAME
              value: "0.0.0.0"
            - name: GRADIO_SERVER_PORT
              value: "7860"
          ports:
            - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: webcam-demo
  namespace: apps
spec:
  selector:
    app: webcam-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webcam-demo
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: webcam-demo.k8s.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webcam-demo
                port:
                  number: 80
    - host: webcam-demo.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-vibrations
                port:
                  number: 80
