---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: buildfarm
  namespace: bazel-buildfarm
spec:
  type: "oci"
  interval: 12h
  url: oci://ghcr.io/buildfarm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazel-buildfarm
  namespace: bazel-buildfarm
spec:
  interval: 12h
  chart:
    spec:
      chart: buildfarm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: buildfarm
      version: 0.2.6
  values:
    server:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      ingress:
        enabled: true
        hosts:
          - host: buildfarm.k8s.local
            paths:
              - path: /
                pathType: Prefix
