---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bazel-buildfarm
  namespace: bazel-buildfarm
spec:
  type: "oci"
  interval: 30m0s
  url: oci://ghcr.io/buildfarm/buildfarm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazel-buildfarm
  namespace: bazel-buildfarm
spec:
  interval: 5m0s
  chart:
    spec:
      chart: bazel-buildfarm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bazel-buildfarm
      version: 0.2.9
  values:
    server:
     resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
      ingress:
        enabled: true
        hosts:
          - host: buildfarm.k8s.local
            paths:
              - path: /
                pathType: Prefix
