---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-set
  namespace: arc-systems
spec:
  interval: 12h
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
      version: 0.10.1
  values:
    githubConfigUrl: https://github.com/Benjamin-Etheredge/mono
    githubConfigSecret: github-token
    containerMode:
      type: "kubernetes"  ## type can be set to dind or kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nfs-csi"
        resources:
          requests:
            storage: 1Gi