---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  namespace: arc-systems
spec:
  type: "oci"
  interval: 12h
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 12h
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
      version: 0.10.1
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
