---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.7.2
  values:
    ingress:
      enabled: true
      host: longhorn.k8s.lan
      ingressClassName: nginx
    csi:
      # needed for microk8s
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
    persistence:
      defaultClassReplicaCount: 2
      defaultDataLocality: "best-effort"
      # TODO
      # recurringJobSelector:
      #   enabled: true
      #   jobList:
      #     - name: trim
      #       cron: "0 0 * * *"
      #       interval: 1d
  interval: 1m0s
