# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta2
# kind: ImageUpdateAutomation
# metadata:
#   name: app
#   namespace: flux-system
# spec:
#   interval: 30m
#   sourceRef:
#     kind: GitRepository
#     name: mono
#   git:
#     checkout:
#       ref:
#         branch: main
#     commit:
#       author:
#         email: fluxcdbot@users.noreply.github.com
#         name: fluxcdbot
#       messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
#     push:
#       branch: main
#   update:
#     path: ./clusters/bale
#     strategy: Setters
