---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic
  namespace: apps
  labels:
    app: semantic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semantic
  template:
    metadata:
      labels:
        app: semantic
    spec:
      containers:
        - name: semantic
          image: docker.io/etheredgeb/semantic:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: semantic
  namespace: apps
spec:
  selector:
    app: semantic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantic
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: semantic.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: semantic
                port:
                  number: 80
    - host: semantic.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tremap
                port:
                  number: 80
