---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 12h
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 12h
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pajikos
      version: 0.2.103
  values:
    persistence:
      enabled: true
      size: 5Gi
    ingress:
      enabled: true
      hosts:
        - host: ha.k8s.local
          paths:
            - path: /
              pathType: Prefix
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 256Mi
    # initContainers:
    #   - name: init-mqtt
    #     image: busybox
    #     command: ['sh', '-c', 'until nslookup mqtt.home-assistant; do echo waiting for mqtt; sleep 2; done;']
