---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: home-assistant
data:
  mosquitto.conf: |
      allow_anonymous false
      listener 1883
      listener 1885
      set_tcp_nodelay true
      persistence_location /mosquitto/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
   metadata:
      labels:
        app: mqtt
   spec:
     containers:
       - name: mqtt
         image: eclipse-mosquitto:latest
         ports:
           - containerPort: 1883
             protocol: TCP
         volumeMounts:
          - mountPath: /mosquitto/data
            name: mqtt-data
          - mountPath: /mosquitto/config
            name: mqtt-config
     volumes:
        - name: mqtt-data
          persistentVolumeClaim:
            claimName: mqtt-pvc
        - name: mqtt-config
          configMap:
            name: mqtt-config
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: home-assistant
spec:
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
