---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia
  namespace: nvidia-gpu-operator
spec:
  interval: 30m0s
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia
  namespace: nvidia-gpu-operator
spec:
  interval: 5m0s
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvidia
      version: v24.9.1
  values:
    # microk8s specific stuff: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#microk8s
    driver:
      enabled: false
    toolkit:
      env:
      - name: CONTAINERD_CONFIG
        value: var/snap/microk8s/current/args/containerd-template.toml
      - name: CONTAINERD_SOCKET
        value: var/snap/microk8s/common/run/containerd.sock 
      - name: CONTAINERD_RUNTIME_CLASS 
        value: nvidia
      - name: CONTAINERD_SET_AS_DEFAULT
        value: "true"

