---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-set-dind
  namespace: arc-runners-set-dind
spec:
  interval: 12h
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: arc-systems
      version: 0.10.1
  values:
    githubConfigUrl: https://github.com/Benjamin-Etheredge/mono
    githubConfigSecret: github-token
    minRunners: 1
    containerMode:
      type: dind
