apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-attu
  namespace: milvus
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: attu
          containerPort: 3000
          protocol: TCP
        env:
        - name: MILVUS_URL
          value: "milvus:19530"
---
apiVersion: v1
kind: Service
metadata:
  name: my-attu-svc
  namespace: milvus
  labels:
    app: attu
spec:
  type: ClusterIP
  ports:
  - name: attu
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: attu
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attu
  namespace: milvus
  labels:
    app: attu
spec:
  ingressClassName: nginx
  rules:
  - host: attu.k8s.lan
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: attu
              port:
                number: 3000