---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zilliztech
  namespace: milvus
spec:
  interval: 30m0s
  url: https://zilliztech.github.io/milvus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus
  namespace: milvus
spec:
  interval: 5m0s
  chart:
    spec:
      chart: milvus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: zilliztech
      version: 4.2.36
  values:
    cluster:
      enabled: false
    minio:
      mode: standalone
      persistence:
        size: 100Gi
    etcd:
      replicaCount: 1
    pulsar:
      enabled: false
    # pulsarv3:
    #   zookeeper:
    #     replicaCount: 1
    #   bookkeeper:
    #     replicaCount: 1
    #     volumes:
    #       journal:
    #         size: 20Gi
    #       ledgers:
    #         size: 40Gi
    #   broker:
    #     replicaCount: 1
    #   proxy:
    #     replicaCount: 1
    ingress:
      enabled: true
      ingresssClassName: nginx
      rules:
        - host: milvus.k8s.lan
          path: "/"
          pathType: "Prefix"
    attu:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - attu.k8s.lan
