apiVersion: apps/v1
kind: Deployment
metadata:
  name: papers
  namespace: apps
  labels:
    app: papers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papers
  template:
    metadata:
      labels:
        app: papers
    spec:
      containers:
        - name: papers
          image: docker.io/etheredgeb/papers:1.0.1 # {"$imagepolicy": "flux-system:papers"}
          # TODO update these to set from env vars
          # env:
          #   - name: GRADIO_SERVER_NAME
          #     value: "0.0.0.0"
          #   - name: GRADIO_SERVER_PORT
          #     value: "7860"
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: papers
  namespace: apps
spec:
  selector:
    app: papers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papers
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - host: papers.k8s.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: papers
                port:
                  number: 80
    - host: papers.etheredge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: papers
                port:
                  number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: papers-harvest
  namespace: apps
spec:
  schedule: "0 0 * * *" # Every day at midnight UTC
  concurrentPolicy: Forbid # Skip job if previous one is still running
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: papers-harvest
              image: docker.io/etheredgeb/papers-harvest:1.0.0 # {"$imagepolicy": "flux-system:papers-harvest"}
              imagePullPolicy: Always
