---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kube-vip
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kube-vip
      version: 0.6.4
  interval: 1m0s
