# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vip
#   namespace: kube-system
# type: Opaque
# stringData:
#   config.address: <IP>
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://kube-vip.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kube-vip
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kube-vip
      version: 0.6.4
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: vip
  values:
    # config:
      # address: <secret>
    env:
      vip_arp: "true"  # mandatory for L2 mode
      lb_enable: "true"
      lb_port: "16443" # changed as microk8s uses 16443 instead of 6443
      vip_cidr: "24"
      cp_enable: "true" # enable control plane load balancing
      svc_enable: "true" # enable user plane load balancing
      vip_leaderelection: "true" # mandatory for L2 mode
      svc_election: "true"
