apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - kube-vip.yaml
  - csi-driver-nfs.yaml
  - sc-nfs.yaml
secretGenerator:
  - name: kube-vip-values
    namespace: kube-system
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
