apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: kube-system
resources:
  - kube-vip.yml
secretGenerator:
  - name: kube-vip-values
    files:
      - values.yaml=values.enc.yaml
