apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-vip.yml
secretGenerator:
  - name: kube-vip-values
    namespace: kube-system
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
