---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller-charts
  namespace: arc-runners-set
spec:
  type: "oci"
  interval: 12h
  url: oci://ghcr.io/actions/actions-runner-controller-charts
